In [1]:
%pip install supervision
%pip -q install roboflow
%pip -q install ultralytics==8.0.28


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 MB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 272.6/272.6 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.2/249.2 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 15.1 MB/s eta 0:00:00


In [2]:
from google.colab import drive
drive.mount('/content/drive')
dataset_location = "/content/drive/MyDrive/CsiLab-BrainTumor-Detection-2"

Mounted at /content/drive


In [3]:
import supervision as sv



In [35]:


ds = sv.DetectionDataset.from_yolo(
      images_directory_path=f"{dataset_location}/test/images",
      annotations_directory_path=f"{dataset_location}/test/labels",
      data_yaml_path=f"{dataset_location}/data.yaml",
      force_masks=False
  )

In [36]:
import random
import supervision as sv

random.seed(10)

MAX_IMAGE_COUNT = 5

n = min(MAX_IMAGE_COUNT, len(ds.images))

keys = list(ds.images.keys())
keys = random.sample(keys, n)

box_annotator = sv.BoxAnnotator()

images = []
titles = []

In [ ]:
detections_list = []
prediction_list = []
for key in keys:
    # Para anotações
    annotation_detections = ds.annotations[key]
    for detection in annotation_detections:
        detections_list.append(detection[0])

    # Para previsões
    prediction_detections = predictions[key]
    for prediction in prediction_detections:
        prediction_list.append(prediction[0])

In [ ]:
import numpy as np


def iou(box1, box2):
    # Verifica se as bounding boxes são válidas.
    if box1[2] is None or box2[2] is None:
        return 0.0

    # Calcula as interseções das bounding boxes.
    inter_top = np.maximum(box1[0], box2[0])
    inter_bottom = np.minimum(box1[2], box2[2])
    inter_left = np.maximum(box1[1], box2[1])
    inter_right = np.minimum(box1[3], box2[3])
    inter_area = (inter_right - inter_left) * (inter_bottom - inter_top)

    # Calcula as áreas das bounding boxes.
    box1_area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2_area = (box2[2] - box2[0]) * (box2[3] - box2[1])

    # Calcula o IoU.
    iou = inter_area / (box1_area + box2_area - inter_area)

    return iou

for i in range(len(detections_list)):
  iou_score = iou(detections_list[i], prediction_list[i])

  # Imprime o IoU.
  print(iou_score)

In [5]:
!yolo detect val  model=/content/drive/MyDrive/5Modelos_Yolov8_DatasetTumor/train2yolov8m/weights/best.pt data=/content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/data.yaml

2023-11-22 17:21:33.544906: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-22 17:21:33.544958: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-22 17:21:33.544992: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 17:21:34.770437: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Ultralytics YOLOv8.0.28 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs
100% 755k/755k [00:00<00:00, 25.5MB/s]
val: Scanning /content/drive/My

In [74]:
import os
import numpy as np
source = '/content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/test'

dados = np.loadtxt('/content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/test/labels/35_jpg.rf.cab669c5610c769bb471aec8910c8175.txt')

id,x2, y2, w2, h2 = dados
print(id,x2,y2,w2,h2)

for filename in os.listdir(f"{source}/labels"):
    f = os.path.join(f"{source}/labels", filename)
    # checking if it is a file
    if os.path.isfile(f):
        print(f)

[          0     0.45391     0.41406     0.23672     0.24297]
0.0 0.45390625 0.4140625 0.23671875 0.24296875


'for filename in os.listdir(f"{source}/labels"):\n    f = os.path.join(f"{source}/labels", filename)\n    # checking if it is a file\n    if os.path.isfile(f):\n        print(f)'

In [69]:
from ultralytics import YOLO
from PIL import Image


model = YOLO('/content/drive/MyDrive/5Modelos_Yolov8_DatasetTumor/train2yolov8m/weights/best.pt')
source = '/content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/test/images/35_jpg.rf.cab669c5610c769bb471aec8910c8175.jpg'

results = model(source)
for r in results:
  print(r.boxes.xywhn.cpu().numpy()[0])


Ultralytics YOLOv8.0.28 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs

image 1/1 /content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/test/images/35_jpg.rf.cab669c5610c769bb471aec8910c8175.jpg: 640x640 1 Tumor, 36.3ms
Speed: 0.6ms pre-process, 36.3ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)


[    0.45703     0.41328     0.22344     0.23281]


In [44]:
detections_list = []
for key in keys:
    # Para anotações
    annotation_detections = ds.annotations[key]
    for detection in annotation_detections:
        detections_list.append(detection[0])
        print(detection[0])
        print(type(annotation_detections),type(detection))


[     202.25      115.75      426.75      278.25]
<class 'supervision.detection.core.Detections'> <class 'tuple'>
[        350      147.75         478      250.25]
<class 'supervision.detection.core.Detections'> <class 'tuple'>
[        400       56.25         569      195.75]
<class 'supervision.detection.core.Detections'> <class 'tuple'>
[     194.75       156.5      320.25       280.5]
<class 'supervision.detection.core.Detections'> <class 'tuple'>
[      304.5       305.5       491.5       517.5]
<class 'supervision.detection.core.Detections'> <class 'tuple'>


In [25]:
!yolo detect predict model =/content/drive/MyDrive/5Modelos_Yolov8_DatasetTumor/train2yolov8m/weights/best.pt source=/content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/test/images/35_jpg.rf.cab669c5610c769bb471aec8910c8175.jpg

2023-11-22 17:43:56.055677: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-22 17:43:56.055734: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-22 17:43:56.055766: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 17:43:57.059102: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Ultralytics YOLOv8.0.28 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs

image 1/1 /content/drive/MyDrive/CsiLab-BrainTumor-Detection-2/test/i